version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.1.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:5.1.0
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    schema-registry:
        image: confluentinc/cp-schema-registry:5.1.0
        depends_on:
            - kafka
            - zookeeper
        environment:
                SCHEMA_REGISTRY_HOST_NAME: schema-registry
                SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
                SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
        ports:
            - "8081:8081"

    rest-proxy-1:
        image: confluentinc/cp-kafka-rest:latest
        depends_on:
            - zookeeper
            - kafka
            - schema-registry
        environment:
                KAFKA_REST_HOST_NAME: rest-proxy-1
                KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
                KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092
                KAFKA_REST_LISTENERS: http://0.0.0.0:8082
                KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        ports:
            - "8082:8082"
    rest-proxy-2:
        image: confluentinc/cp-kafka-rest:latest
        depends_on:
            - zookeeper
            - kafka
            - schema-registry
        environment:
                KAFKA_REST_HOST_NAME: rest-proxy-2
                KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
                KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092
                KAFKA_REST_LISTENERS: http://0.0.0.0:8082
                KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        ports:
            - "8083:8082"
    rest-proxy-3:
        image: confluentinc/cp-kafka-rest:latest
        depends_on:
            - zookeeper
            - kafka
            - schema-registry
        environment:
                KAFKA_REST_HOST_NAME: rest-proxy-3
                KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
                KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092
                KAFKA_REST_LISTENERS: http://localhost:8084
                KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        ports:
            - "8084:8082"

    ksql-server:
        image: "confluentinc/cp-ksql-server:5.1.0"
        depends_on:
            - kafka
            - schema-registry
        environment:
            KSQL_BOOTSTRAP_SERVERS: kafka:29092
            KSQL_LISTENERS: http://0.0.0.0:8088
            KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        ports:
            - "8088:8088"
    kafka-ui:
        image: quay.io/cloudhut/kowl:master
        ports:
            - 8010:8080
        links:
            - kafka
            - zookeeper
            - schema-registry
        depends_on:
            - zookeeper
            - kafka
            - schema-registry
        environment:
            KAFKA_BROKERS: "kafka:29092"
    nginx:
        build: ./nginx 
        ports:
            - "8001:80" 
        links:
            - rest-proxy-1
            - rest-proxy-2
            - rest-proxy-3
        depends_on:
            - rest-proxy-1
            - rest-proxy-2
            - rest-proxy-3